:-[satisfy,induce_ifthen,automatica2].

learn_rules:-
	learn('Francesinha'),
    learn('Salada de feijao preto'),
    learn('Pizza'),
    learn('Arroz de pato'),
    learn('Lasanha'),
    learn('Prego no pao'),
    learn('Cozido a portuguesa'),
    learn('Sushi'),
    learn('Migas de bacalhau'),
    learn('Lasanha de Espinafres'),
    learn('Mac'),
    learn('Francesinha'),
    learn('Empadao de legumes'),
    learn('Salada de frango'),
    learn('Francesinha'),
    learn('salmao grelhado'),
    learn('Massa com grao de bico'),
    learn('Massa bolonhesa'),
    learn('Pizza'),
    learn('Lulas recheadas'),
    learn('chili de legumes'),
    learn('chili'),
    learn('Arroz de cabidela'),
    learn('Bacalhau'),
    learn('Bacalhau Braga'),
    learn('Cabidela'),
    learn('Arroz de polvo com filetes de polvo'),
    learn('Cabrito assado'),
    learn('Salada de frango'),
    learn('Rojoes'),
    learn('Almondegas'),
    learn('Sushi'),
    learn('Salada de lentilhas'),
    learn('Francesinha'),
    learn('Pizza'),
    learn('Carne de porca a alentejana'),
    learn('Filetes de pescada'),
    learn('Bacalhau com broa'),
    learn('Polvo a lagareiro'),
    learn('Lulas grelhadas'),
    learn('Arroz de pato'),
    learn('Arroz de marisco'),
    learn('Lasanha'),
    learn('Pica no chao'),
    learn('Arroz de sangue'),
    learn('Empadao'),
    learn('Bacalhau Braga'),
    learn('Panados com arroz'),
    learn('Bacalhau'),
    learn('Picanha grelhada a naco'),
	
	tell('ifthen.pl'),
	listing(<==),
	told.
